services:
  - type: web
    name: fashion-backend
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/Shopping-Website-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: fashion-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: fashion-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: fashion-db
          property: password
databases:
  - name: fashion-db
    plan: free
    databaseName: fashion
    user: fashion_user
